# Generated by Django 5.0.1 on 2024-02-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_exerciselist_alter_exercise_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_exercise', to='base.exercise'),
        ),
    ]
