# Generated by Django 5.0.1 on 2024-02-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_exercise_workout_workout_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(default='My workout', max_length=200),
        ),
    ]
