# Generated by Django 5.0.1 on 2024-02-05 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_workout_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-created']},
        ),
    ]
