# Generated by Django 5.0.1 on 2024-02-08 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_workout_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.goalsmodel'),
        ),
    ]
