# Generated by Django 5.0.1 on 2024-02-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='base.exercise'),
        ),
    ]
