# Generated by Django 5.0.1 on 2024-02-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_workout_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
