# Generated by Django 5.0.1 on 2024-02-08 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.goalsmodel'),
        ),
    ]
